name: Sync to Azure Repos

on:
  push:
    branches:
      - main  # or 'master' if you're using that

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3

    - name: Push to Azure DevOps Repo
      env:
        AZURE_PAT: ${{ secrets.AZURE_PAT }}
      run: |
        git config --global user.email "LEADKRISHNA18@GMAIL.COM"
        git config --global user.name "VENKATA SAI KRISHNA MARIYALA"

        git remote add azure https://MVSK1156:${ADqV81B24jjBTEFSjWaE6RNWKRn4HubdvPtZthtrd4zmORktMzOwJQQJ99BFACAAAAAAAAAAAAASAZDO3lKt}@dev.azure.com/YOUR_ORG/YOUR_PROJECT/_git/YOUR_REPO

        git push azure HEAD:main --force
