name: Sync to Azure Repos

on:
  push:
    branches:
      - main  # or 'master' if that's your branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3

    - name: Push to Azure DevOps Repo
      env:
        AZURE_PAT: ${{ secrets.AZURE_PAT }}
      run: |
        git config --global user.email "LEADKRISHNA18@GMAIL.COM"
        git config --global user.name "VENKATA SAI KRISHNA MARIYALA"

        git remote add azure https://LEADKRISHNA180216:${AZURE_PAT}@dev.azure.com/LEADKRISHNA180216/MVSK1156/_git/MVSK1156

        git push azure HEAD:main --force
